[package]
name = "lc3-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
clap = { version = "4.0.18", features = ["derive"] }
termios = "0.3.1"
structopt = "0.3.22"